<?php
class EmgDivisi extends Model{
    protected $alias='divisi';
    protected $columns=array(
        'nama'=>'VARCHAR(128)',
    );
    protected $firstdata=array(
        array('id'=>1,'nama'=>'SSU KORPORAT'),
        array('id'=>2,'nama'=>'BIDANG ADMINISTRASI KEUANGAN'),
        array('id'=>3,'nama'=>'BIDANG FASILITAS'),
        array('id'=>4,'nama'=>'BIDANG LOGISTIK DAN IVENTORI'),
        array('id'=>5,'nama'=>'BIDANG PERENCANAAN PENGADAAN DAN SOURCING'),
        array('id'=>6,'nama'=>'BIDANG PELAKSANAAN PENGADAAN'),
        array('id'=>7,'nama'=>'BIDANG PENGENDALIAN KONTRAK DAN QA'),
        array('id'=>8,'nama'=>'BIDANG PELAYANAN SDM'),
        array('id'=>9,'nama'=>'SATUAN AUDIT INTERNAL'),
        array('id'=>10,'nama'=>'BIDANG PENGAWASAN INTERNAL BISNIS'),
        array('id'=>11,'nama'=>'BIDANG PENGAWASAN INTERNAL KEPATUHAN'),
        array('id'=>12,'nama'=>'BIDANG PERENCANAAN DAN PENGAWASAN SISTEM AUDIT'),
        array('id'=>13,'nama'=>'SATUAN PENGENDALIAN KINERJA KORPORAT'),
        array('id'=>14,'nama'=>'BIDANG ANALISA DAN EVALUASI KINERJA KORPORAT'),
        array('id'=>15,'nama'=>'BIDANG MANAJEMEN RISIKO'),
        array('id'=>16,'nama'=>'BIDANG PELAPORAN DAN MONITORING'),
        array('id'=>17,'nama'=>'BIDANG PERENCANAAN KORPORAT'),
        array('id'=>18,'nama'=>'SEKRETARIAT PERUSAHAAN'),
        array('id'=>19,'nama'=>'BIDANG HUBUNGAN LEMBAGA'),
        array('id'=>20,'nama'=>'BIDANG HUKUM KORPORAT'),
        array('id'=>21,'nama'=>'SUB DIR HCM DAN K3'),
        array('id'=>22,'nama'=>'BIDANG DELIVERY SERVICES'),
        array('id'=>23,'nama'=>'BIDANG HUMAN CAPITAL DEVELOPMENT'),
        array('id'=>24,'nama'=>'BIDANG KEBIJAKAN SDM DAN K3'),
        array('id'=>25,'nama'=>'BIDANG RENCANA SUMBER DAYA BISNIS DAN ORGANISASI'),
        array('id'=>26,'nama'=>'SUB DIR KEUANGAN'),
        array('id'=>27,'nama'=>'BIDANG AKUNTANSI'),
        array('id'=>28,'nama'=>'BIDANG BILLING'),
        array('id'=>29,'nama'=>'BIDANG CORPORATE FINANCE'),
        array('id'=>30,'nama'=>'BIDANG TREASURY'),
        array('id'=>31,'nama'=>'SUB DIR KUALITAS LAYANAN OPERASI'),
        array('id'=>33,'nama'=>'BIDANG KEBIJAKAN STANDAR DAN PROSEDUR'),
        array('id'=>34,'nama'=>'BIDANG MANAJEMEN ASET'),
        array('id'=>35,'nama'=>'BIDANG QUALITY DAN PERFORMANCE'),
        array('id'=>36,'nama'=>'SUB DIR KAPASITAS DAN CAKUPAN LAYANAN'),
        array('id'=>37,'nama'=>'BIDANG PERENCANAAN DAN TEKNOLOGI JARINGAN'),
        array('id'=>38,'nama'=>'BIDANG PMO'),
        array('id'=>39,'nama'=>'BIDANG RENCANA KAPASITAS DAN CAKUPAN JARINGAN'),
        array('id'=>40,'nama'=>'SSU KETENAGALISTRIKAN'),
        array('id'=>41,'nama'=>'BIDANG CONTACT CENTER & SERVICE DESK'),
        array('id'=>43,'nama'=>'BIDANG PENDAPATAN SEGMEN GOVERNMENT'),
        array('id'=>44,'nama'=>'BIDANG SALES DAN KONTRAK'),
        array('id'=>45,'nama'=>'BIDANG MODEL BISNIS KETENAGALISTRIKAN'),
        array('id'=>46,'nama'=>'BIDANG PENDAPATAN SEGMEN OPERATOR'),
        array('id'=>47,'nama'=>'BIDANG MANAJEMEN PORTOFOLIO'),
        array('id'=>48,'nama'=>'BIDANG DESAIN LAYANAN MANAGED SERVICES'),
        array('id'=>49,'nama'=>'BIDANG EKSEKUSI LAYANAN BISNIS'),
        array('id'=>50,'nama'=>'BIDANG PENDAPATAN SEGMEN ENTERPRISE'),
        array('id'=>51,'nama'=>'BIDANG PENDAPATAN SEGMEN BANKING'),
        array('id'=>52,'nama'=>'BIDANG SALES SUPPORT & EVALUASI PENJUALAN'),
        array('id'=>53,'nama'=>'BIDANG SUPPORTING JUAL, AKTIVASI & PEMELIHARAAN'),
        array('id'=>54,'nama'=>'BIDANG SHARED SERVICES UNIT OPERASI TI PUBLIK'),
        array('id'=>55,'nama'=>'BIDANG RESOURCE MANAGEMENT'),
        array('id'=>56,'nama'=>'BIDANG PENGEMBANGAN LAYANAN SOLUSI TI 2'),
        array('id'=>57,'nama'=>'BIDANG OPEN ACCSESS'),
        array('id'=>58,'nama'=>'BIDANG RITEL'),
        array('id'=>59,'nama'=>'BIDANG ALIANSI STRATEGIS & REGULASI'),
        array('id'=>60,'nama'=>'BIDANG FASILITAS'),
        array('id'=>61,'nama'=>'BIDANG CONFIGURATION MANAGEMENT'),
        array('id'=>62,'nama'=>'BIDANG CUSTOMER LOYALTY'),
        array('id'=>63,'nama'=>'BIDANG DATA CENTER'),
        array('id'=>64,'nama'=>'BIDANG FASILITAS'),
        array('id'=>65,'nama'=>'BIDANG FAULT MANAGEMENT'),
        array('id'=>66,'nama'=>'BIDANG INVENTORY'),
        array('id'=>67,'nama'=>'BIDANG MANAGED SERVICE ROUTER & TI'),
        array('id'=>68,'nama'=>'BIDANG MULTIMEDIA'),
        array('id'=>69,'nama'=>'BIDANG PREMIUM ACCOUNT PLN'),
        array('id'=>70,'nama'=>'BIDANG TI OSS'),
        array('id'=>71,'nama'=>'BIDANG MANAGED SERVICE PC LAPTOP'),
        array('id'=>72,'nama'=>'BIDANG MANAGED SERVICE ROUTER & TI'),
        array('id'=>73,'nama'=>'BIDANG ALIANSI STRATEGIS & REGULASI'),
        array('id'=>75,'nama'=>'BIDANG EKSEKUSI LAYANAN BISNIS'),
        array('id'=>76,'nama'=>'BIDANG KINERJA PENJUALAN APLIKASI KETENAGALISTRIKA...'),
        array('id'=>77,'nama'=>'BIDANG KINERJA PENJUALAN NON APLIKASI KETENAGALIST...'),
        array('id'=>78,'nama'=>'BIDANG MANAGED SERVICES PC LAPTOP'),
        array('id'=>79,'nama'=>'BIDANG MANAJEMEN LAYANAN DAN QA'),
        array('id'=>80,'nama'=>'BIDANG MANAJEMEN PORTOFOLIO'),
        array('id'=>81,'nama'=>'BIDANG MODEL BISNIS KETENAGALISTRIKAN'),
        array('id'=>82,'nama'=>'BIDANG OPEN ACCESS'),
        array('id'=>83,'nama'=>'BIDANG OPERASIONAL BPO'),
        array('id'=>84,'nama'=>'BIDANG PEMELIHARAAN & PENGEMBANGAN INFRASTRUKTUR T...'),
        array('id'=>85,'nama'=>'BIDANG PEMELIHARAAN APLIKASI'),
        array('id'=>86,'nama'=>'BIDANG PENGENDALIAN & MONITORING KETENAGALISTRIKAN'),
        array('id'=>87,'nama'=>'BIDANG PERENCANAAN ARSITEKTUR KETENAGALISTRIKAN'),
        array('id'=>88,'nama'=>'BIDANG PRODUK & PEMASARAN'),
        array('id'=>89,'nama'=>'BIDANG RESOURCE MANAGEMENT 1'),
        array('id'=>90,'nama'=>'BIDANG RESOURCE MANAGEMENT 2'),
        array('id'=>91,'nama'=>'BIDANG RITEL'),
        array('id'=>92,'nama'=>'BIDANG SISTEM & PROSEDUR KETENAGALISTRIKAN'),
        array('id'=>93,'nama'=>'BIDANG SOLUSI TI & IMPLEMENTASI KETENAGALISTRIKAN ...'),
        array('id'=>94,'nama'=>'BIDANG SOLUSI TI & IMPLEMENTASI KETENAGALISTRIKAN ...'),
        array('id'=>95,'nama'=>'BIDANG FASILITAS'),
        array('id'=>96,'nama'=>'BIDANG HELPDESK MRSTI'),
    );

}
